// frontend/src/pages/Login.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useUser } from '@/context/AppContext';

const API_BACKEND_URI = `${import.meta.env.VITE_BACKEND_URL}/api/v1`;

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useUser();
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      const response = await fetch(`${API_BACKEND_URI}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username: email, password }),
      });

      if (response.ok) {
        const data = await response.json();
        login(data.user, data.access_token);
        navigate('/home');
      } else {
        const data = await response.json();
        setError(data.detail || 'Incorrect email or password. Please try again.');
      }
    } catch {
      setError('Unable to connect. Please check your internet connection and try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">Welcome back</h1>
          <p className="text-gray-400">Sign in to continue to your workspace</p>
        </div>
        
        <div className="bg-gray-800/50 backdrop-blur-sm rounded-2xl p-8 border border-gray-700/50 shadow-xl">
          <form onSubmit={handleLogin} className="space-y-5">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-300 mb-2">
                Email address
              </label>
              <input
                type="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                placeholder="you@example.com"
                required
                autoComplete="email"
              />
            </div>
            
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-300 mb-2">
                Password
              </label>
              <input
                type="password"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                placeholder="Enter your password"
                required
                autoComplete="current-password"
              />
            </div>

            {error && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
                <p className="text-sm text-red-400">{error}</p>
              </div>
            )}
            
            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-3 px-4 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isLoading ? (
                <>
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Signing in...
                </>
              ) : (
                'Sign in'
              )}
            </button>
          </form>
          
          <p className="mt-6 text-center text-gray-400">
            Don't have an account?{' '}
            <Link to="/signup" className="text-blue-400 hover:text-blue-300 font-medium transition-colors">
              Create one
            </Link>
          </p>
        </div>
        
        <p className="mt-6 text-center text-gray-500 text-sm">
          By signing in, you agree to our terms and privacy policy
        </p>
      </div>
    </div>
  );
}

// frontend/src/routes/Login.svelte
<script lang="ts">
  import { navigate } from "svelte-routing";
  import { API_BACKEND_URI } from "../common/constants";
  import { userStore } from "../common/stores";

  let email = "";
  let password = "";
  let error = "";

  async function handleLogin() {
    try {
      const response = await fetch(`${API_BACKEND_URI}/auth/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username: email, password }),
      });

      if (response.ok) {
        const data = await response.json();
        userStore.login(data.user, data.access_token);
        navigate("/");
      } else {
        const data = await response.json();
        error = data.detail || "Login failed";
      }
    } catch (err) {
      error = "An error occurred during login";
    }
  }
</script>

<div class="container">
  <h1>Log In</h1>
  <form on:submit|preventDefault={handleLogin}>
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" id="email" bind:value={email} required />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" id="password" bind:value={password} required />
    </div>
    {#if error}
      <p class="error">{error}</p>
    {/if}
    <button type="submit" class="btn">Log In</button>
  </form>
  <p>Don't have an account? <a href="/signup">Sign up</a></p>
</div>

<style>
  .container {
    max-inline-size: 400px;
    margin-inline: auto;
    padding-block: 2rem;
    padding-inline: 1rem;
  }

  h1 {
    text-align: center;
    margin-block-end: 2rem;
  }

  .form-group {
    margin-block-end: 1rem;
  }

  label {
    display: block;
    margin-block-end: 0.5rem;
  }

  input {
    inline-size: 100%;
    padding-block: 0.5rem;
    padding-inline: 0.75rem;
    border: 1px solid var(--bg-2);
    border-radius: 4px;
    background-color: var(--bg-1);
    color: var(--fg-1);
  }

  .error {
    color: #ff3e00;
    margin-block-end: 1rem;
  }

  .btn {
    inline-size: 100%;
    padding-block: 0.75rem;
    background-color: var(--fg-1);
    color: var(--bg-1);
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .btn:hover {
    background-color: var(--fg-2);
  }

  p {
    text-align: center;
    margin-block-start: 1rem;
  }

  a {
    color: var(--fg-1);
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }
</style>
