// frontend/src/App.svelte
<script lang="ts">
  import { Router, Route } from "svelte-routing";
  import Sidebar from "./lib/Sidebar.svelte";
  import Home from "./routes/Home.svelte";
  import Agents from "./routes/Agents.svelte";
  import Container from "./lib/Container.svelte";
  import AgentPage from "./routes/AgentPage.svelte";
  import Tasks from "./routes/Tasks.svelte";
  import TaskPage from "./routes/TaskPage.svelte";
  import Teams from "./routes/Teams.svelte";
  import TeamPage from "./routes/TeamPage.svelte";
  import TeamInteraction from './routes/TeamInteraction.svelte';
  import Signup from "./routes/Signup.svelte";
  import Login from "./routes/Login.svelte";
  import { webSocketStore, userStore } from "./common/stores";
  import { onMount } from "svelte";
  import ThemeToggle from "$lib/ThemeToggle.svelte";
  import "./app.css";

  let user: any = $state();

  userStore.subscribe((value) => {
    user = value;
    console.log("User:", user);
  });

  onMount(() => {
    userStore.checkAuth();
    webSocketStore.connect();
  });

  interface Props {
    url?: string;
  }

  let { url = '' }: Props = $props();
</script>

<Router {url}>
  <div class="main-container">
    {#if user}
      <Sidebar></Sidebar>
    {/if}
    <Container>
      <Route path="/" component={user ? Home : Login}></Route>
      <Route path="/:session_id" component={Home}></Route>
      <Route path="/c/:agent_id" component={Home}></Route>
      <Route path="/signup" component={Signup}></Route>
      <Route path="/login" component={Login}></Route>
      <Route path="/agents" component={Agents}></Route>
      <Route path="/agents/new" component={AgentPage}></Route>
      <Route path="/agents/:agent_id" component={AgentPage}></Route>
      <Route path="/tasks" component={Tasks}></Route>
      <Route path="/tasks/new" component={TaskPage}></Route>
      <Route path="/tasks/:task_id" component={TaskPage}></Route>
      <Route path="/teams" component={Teams}></Route>
      <Route path="/teams/new" component={TeamPage}></Route>
      <Route path="/teams/:team_id" component={TeamPage}></Route>
      <Route path="/teams/:team_id/interact" >
        {#snippet children({ params })}
                <TeamInteraction team_id={params.team_id} />
                      {/snippet}
            </Route>
      <Route path="/teams/:team_id/tasks/:task_id/interact" >
        {#snippet children({ params })}
                <TeamInteraction team_id={params.team_id} task_id={params.task_id} />
                      {/snippet}
            </Route>
      <Route
        path="/teams/:team_id/tasks/:task_id/sessions/:session_id/interact"
        
      >
        {#snippet children({ params })}
                <TeamInteraction
            team_id={params.team_id}
            task_id={params.task_id}
            session_id={params.session_id}
          />
                      {/snippet}
            </Route>
    </Container>
  </div>
</Router>

<style>
  .main-container {
    block-size: 100vh;
    position: relative;
    display: flex;
    justify-content: space-between;
    gap: 20px;
  }
</style>

// frontend/src/App.tsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { UserProvider, useUser } from '@/context/AppContext';
import Sidebar from '@/components/Sidebar';
import Home from '@/pages/Home';
import Login from '@/pages/Login';
import Signup from '@/pages/Signup';
import Agents from '@/pages/Agents';
import AgentPage from '@/pages/AgentPage';
import Tasks from '@/pages/Tasks';
import TaskPage from '@/pages/TaskPage';
import Teams from '@/pages/Teams';
import TeamPage from '@/pages/TeamPage';
import TeamInteraction from '@/pages/TeamInteraction';
import '@/app.css';

function ProtectedRoute({ children }: { children: React.ReactNode }) {
  const { user } = useUser();
  if (!user) return <Navigate to="/" replace />;
  return <>{children}</>;
}

function AppRoutes() {
  const { user } = useUser();
  
  return (
    <Routes>
      <Route path="/" element={user ? <Navigate to="/home" replace /> : <Login />} />
      <Route path="/signup" element={user ? <Navigate to="/home" replace /> : <Signup />} />
      <Route 
        path="/home" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <Home />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/agents" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <Agents />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/agents/new" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <AgentPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/agents/:agentId" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <AgentPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/tasks" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <Tasks />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/tasks/new" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TaskPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/tasks/:taskId" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TaskPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <Teams />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams/new" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TeamPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams/:teamId" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TeamPage />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams/:teamId/interact" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TeamInteraction />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams/:teamId/tasks/:taskId/interact" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TeamInteraction />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route 
        path="/teams/:teamId/tasks/:taskId/sessions/:sessionId/interact" 
        element={
          <ProtectedRoute>
            <div className="flex h-screen">
              <Sidebar />
              <TeamInteraction />
            </div>
          </ProtectedRoute>
        } 
      />
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
}

export default function App() {
  return (
    <BrowserRouter>
      <UserProvider>
        <AppRoutes />
      </UserProvider>
    </BrowserRouter>
  );
}
